[project]
name = "taxi_rides_ny"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-bigquery>=1.11.0",
    "dbt-core>=1.11.5",
    "dbt-duckdb>=1.10.0",
]
